services:
  mysqldb:
    image: mysql:8
    container_name: mysql-practical
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cleaner
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: somesh150805/2300031960-exam-backend:latest
    container_name: springboot-prac
    ports:
      - "2025:4000"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: somesh150805/2300031960-exam-frontend:latest
    container_name: react-prac
    ports:
      - "2001:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
